### PR TITLE
Workflow Job compatibility

### PR DESCRIPTION
**Pull request by schulzh**
This PR adds the ability to trigger workflow jobs.
I couldn't get it to build with these `@inheritDoc` annotations, so I removed them.

### CODE REVIEW

**Comment by rinrinne** [comment]
You should split this to at least 3 PRs. Regarding "@inheritDoc", maybe it is IDEA issue because I cannot see any errors on Eclipse. It should be solved within IDEA environment.

**Comment by schulzh** [comment]
What should I split into 3 PRs? All thsese changes (except of course the `@inheritdoc`) is necessary to get it working for workflow jobs.
I did not get it to build with the annotation via Maven, it is not an IDEA issue.

**Comment by rinrinne** [comment]
Yes, your commit updates version for each modules. It should be decoupled from any functional changes.

"@inheritdoc" is not annotation but javadoc tag. I have never seen build issues for this tag on HEAD. Maybe it was introduced by bumping module version. Anyway, I think you should identify the root cause of issue regarding "@inheritdoc".

**Comment by schulzh** [comment]
The necessary `ParameterizedJobMixIn` is first available in Jenkins LTS 1.625, so it is necessary for Workflow compatibility. This change in turn requires commons.lang > 3.6.
Updating rabbitmq.consumer.version was unnecessary, I've remove it.
`@inheritdoc` is also working now, so I added them back.

**Comment by rinrinne** [comment]
Thanks!

**Comment by rinrinne** [comment]
Released 2.5.

**Comment by rinrinne** [comment]
Hi @schulzh , can you use pipeline? If yes, could you try to use #8?
I found the way to contribute this plugin to declarative pipeline, but I have no available Jenkins clusters at least until the end of this month...

So I would like someone to test it if possible.

**Comment by schulzh** [comment]
Sure, I can test it.
However, when I try to build the symbol branch, I cannot get it to build again because of the javadoc tags: https://gist.github.com/schulzh/d2958684b142969741e4eff91565aa01
Maybe I am missing some maven goal?

**Comment by schulzh** [comment]
According to https://stackoverflow.com/questions/13327534/details-of-difference-between-see-and-inheritdoc, `@inheritdoc` is redundant when not adding more documentation. Maybe removing them was not bad after all?

**Comment by rinrinne** [comment]
Thank for sharing info and your build log!!

Unfortunately I could not reproduce your issue but found some wrong points. I will update symbol branch.

BTW, I found the gap between us in build log.
* You are using JDK8, but I'm using JDK7. I switched to JDK8 then built once (success without new patch).
* You are building on Windows, but I'm on Linux.

**Pull request merged**
